# Generated by Django 2.0.5 on 2018-10-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_auto_20181017_1916'),
    ]

    operations = [
    ]
