# Generated by Django 2.0.5 on 2018-10-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_auto_20181018_0128'),
    ]

    operations = [
    ]
