# Generated by Django 2.0.5 on 2018-10-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0004_auto_20181018_0129'),
    ]

    operations = [
    ]
